trigger:
- main

pool:
  name: Default

variables:
  ARM_CLIENT_ID: $(ARM_CLIENT_ID)
  ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
  ARM_TENANT_ID: $(ARM_TENANT_ID)
  ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)


stages:
- stage: Terraform
  jobs:
  - job: ApplyInfra
    steps:

    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: '1.5.0'

    # Debug (temporary)
    - script: |
        echo CLIENT_ID=$(ARM_CLIENT_ID)
        echo TENANT_ID=$(ARM_TENANT_ID)
      displayName: "Debug Variables"

    - script: terraform init
      displayName: "Terraform Init"

    - script: terraform plan
      displayName: "Terraform Plan"

    - script: terraform apply -auto-approve
      displayName: "Terraform Apply"